### PR TITLE
Wording change on line 177

### PR DESCRIPTION
**Pull request by eth0net**

### CODE REVIEW

**Review by nearnshaw — APPROVED** [review]
Thanks for your contribution @Raziel2244!
I'm merging your change :)

**Comment by eth0net** [comment]
Thanks, glad I could help in some way :)

**Comment by eth0net** [comment]
Is this safe to close now? @nearnshaw :)

**Comment by nearnshaw** [comment]
Hey @Raziel2244, we're having a bit of difficulty getting your contribution to pass our automated continuous integration tests, probably because it comes from a user who isn't a member of the organization. We're working on fixing that. 
We really care about making it possible for community members to contribute to our docs and get credit for it on their GitHub profiles.
Please keep the pull request open and we will merge it as soon as we fix our pipeline problems.
Thanks,
Nico

**Comment by eth0net** [comment]
Okay, thanks :)

**Pull request merged**
