### PR TITLE
Russian translation

### PR DESCRIPTION
**Pull request by kmtz**

### CODE REVIEW

**Comment by kmtz** [comment]
Partial at this moment, still working on it.

**Comment by kmtz** [comment]
Oops, accidentally sent it to master, my bad, poor git experience.

**Comment by nearnshaw** [comment]
@kmtz  we appreciate your efforts to translate the documentation into Russian, however we don't plan to officially support a version in that language in our docs site. That's because the content in the docs changes constantly, and keeping it up to date in several languages is a real challenge. With technical documentation, having a document that's out of date can sometimes do more harm than good because it can end up showing obsolete code. 
We're currently only doing a Chinese version and possibly Korean in the future because that's where we see we have the largest markets.
You're of course free and welcome to host a Russian version of the docs anywhere you want, but we're not ready to take on the responsibility to keep that up to date in the official site.
Thanks again for your willingness to help!

**Comment by kmtz** [comment]
Well, anyway I will continue working and keep it up-to day in my repo.

**Comment by kmtz** [comment]
Maybe it makes sense to create a repo here, even if you don't plan to publish it to the web-site? THe developers will most likely visit this github and I would be happy if it will help somebody.

**Pull request closed without merging**
