### PR TITLE
chore: Update publication fees

### PR DESCRIPTION
**Pull request by fzavalia**

### CODE REVIEW

**Review by nearnshaw — APPROVED** [review]

**Comment by nearnshaw** [comment]
@fzavalia 
approved, but please fix the conflifts before merging


also, please implement the same changes in the future repository of the docs
this repository is still live, but will be deprecated once we publish the new docs site
https://github.com/decentraland/documentation-creators

**Comment by fzavalia** [comment]
@nearnshaw Resolved the conflict

**Comment by fzavalia** [comment]
@nearnshaw https://github.com/decentraland/documentation-creators/pull/7

**Comment by fzavalia** [comment]
> @nearnshaw [decentraland/documentation-creators#7](https://github.com/decentraland/documentation-creators/pull/7)

Here is the changes in the new repo

**Pull request merged**
