### PR TITLE
Add Linux hardware acceleration guide

### PR DESCRIPTION
**Pull request by OverShifted**

### CODE REVIEW

**Review by nearnshaw — APPROVED** [review]

**Comment by nearnshaw** [comment]
Thanks @OverShifted for your contribution, we really appreciate it!

I just did some minor tweaks so that the tone matches that of the rest of the docs
And I also moved these instructions to the end, as most players will likely be using Windows or Mac, and these more complicated steps are more intimidating to beginners.

I'm merging your PR now, the changes should be published to the site automatically in a few minutes :)

**Comment by OverShifted** [comment]
@nearnshaw It was the second PR in my life 😬.

Why the content on the website is not updated yet? 🤔

**Comment by nearnshaw** [comment]
@OverShifted
Ohh weird that it's not there. It should be published by now, the process is automatic, but I don't see it either. I'll ask the devs that handle that. Thanks for letting us know!

**Comment by nearnshaw** [comment]
@OverShifted 
the build was just fixed, and now it's published :)

**Pull request merged**
