### PR TITLE
feat: add new parcels endpoints

### PR DESCRIPTION
**Pull request by nachomazzara**
Blocked by decentraland/marketplace#920

### CODE REVIEW

**Comment by menduz** [comment]
What is that parcel ID? `1.15792089237316195423570985008687907837276713420356456256678977458620023701475e+77`

If the server can resolve that number it is far from correct.

**Comment by nachomazzara** [comment]
> What is that parcel ID? `1.15792089237316195423570985008687907837276713420356456256678977458620023701475e+77`
> 
> If the server can resolve that number it is far from correct.

Is the way we store the parcel `token_id` in our DB. I removed it from the documentation in order to avoid error-prone.

**Comment by menduz** [comment]
are we storing `token_id` as a varchar or as a number? if it is a number we should change it, because DB numbers goes to 64bit and that number is a 256bit number

**Comment by nachomazzara** [comment]
> are we storing `token_id` as a varchar or as a number? if it is a number we should change it, because DB numbers goes to 64bit and that number is a 256bit number

As a `text` (varchar).

**Comment by menduz** [comment]
So we have a .toNumber convertion somewhere. look at the end of the number `1.15...75e+77` and back to text again @nicosantangelo FYI

**Comment by nachomazzara** [comment]
> So we have a .toNumber convertion somewhere. look at the end of the number `1.15...75e+77` and back to text again @nicosantangelo FYI

Right, we are aware of that. We use it just for internal reference, we don't expose that to the users. We   are evaluating of converting them to hexa

**Comment by menduz** [comment]
sabe

**Comment by nachomazzara** [comment]
@menduz @nearnshaw can we merge it?

**Comment by nearnshaw** [comment]
👍  fine by me
it looks like @nicosantangelo is set as a reviewer, so we need him to sign before we can merge

**Comment by nachomazzara** [comment]
Oh, yes I set him. Ping @nicosantangelo

**Review by nicosantangelo — APPROVED** [review]

**Comment by nicosantangelo** [comment]
LGTM !

**Comment by nearnshaw** [comment]
@nachomazzara looks like one of the commits wasn't signed with a youbikey :/
That means I can't merge this myself, we need to override it manually

@eordano or @adrabenche could you please merge this branch with an override of the security checks?

**Comment by nicosantangelo** [comment]
I can do it

**Pull request merged**
